python /home/denggf/Desktop/LPSGM-main/preprocess_data/HANG7.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/SYSU.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/DOD-H.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/DOD-O.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/APPLES.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/HOMEPAP.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/STAGES_1.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/STAGES_2.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/NCHSDB.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/MROS.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/SVUH.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/SHHS.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/CFS.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/DCSM.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/HMC.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/CCSHS.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/ABC.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/CHAT.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/ISRUC.py
python /home/denggf/Desktop/LPSGM-main/preprocess_data/P2018.py
